# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mactop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/metaspartan/mactop"
  version "2.0.6"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/metaspartan/mactop/releases/download/v2.0.6/mactop_2.0.6_darwin_arm64.tar.gz"
    sha256 "4a85ccb5a471c34b2031b4af18801fb9148930c02c151016b6c3cb4adb3435e1"

    def install
      bin.install "mactop"
    end
  end

  def caveats
    <<~EOS
      mactop requires macOS 12+, and runs exclusively on Apple Silicon.
    EOS
  end
end
